### ISSUE TITLE
FEAT: HomeView 구현

### ISSUE THREAD

**Issue by minyoy** [umc-hackathon-ios/iOSHackathon#3]
# 🔨 Describe
- 총 공부시간, 각 공부, 휴식시간 설정 뷰와 홈 뷰를 생성하고 API를 연결합니다.

# ✅ Tasks
- [ ] 총 공부시간 설정 뷰 생성
- [ ] 공부, 휴식시간 설정 뷰 생성
- [ ] 홈 뷰 생성
- [ ] 과목 추가 모달 생성
